site_name: 'ESIIL Team Science'
site_description: 'Central resource for ESIIL Team Science'
site_author: Kayleigh Ward
site_url: https://cu-esiil.github.io/Team-Science

# Repository
repo_name: Team-Science
repo_url: https://github.com/CU-ESIIL/Team-Science
edit_uri: edit/main/docs/
# Copyright
copyright: 'Copyright &copy; 2023 University of Colorado Boulder'

# Page tree
nav:
  - Home: index.md
  - Research Projects: 
       - Meta-analysis: add markdown file under resources directory
       - Observational study: add markdown file
       - Cross-center study: add markdown file      
  - Working Group Training Resources:
       - Workshops: add a markdown file with links to zenodo trainings and recordings under resources directory
  - Dive into Team Science:
        - Explainers: add a markdown file with links to zenodo explainers under resources directory
        - Resources: add a markdown file with links to zenodo resources and recordings under resources directory

# Configuration
theme:
  highlightjs: true
  name: material
  font:
    text: 'Open Sans'
    code: 'Roboto Mono'
  logo: 'assets/ESIIL_logo.png'
  favicon: 'assets/favicon.ico'
  # setting features for the navigation tab
  features:
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - toc.follow
    - content.code.copy
  # Default values, taken from mkdocs_theme.yml
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: white)"
      primary: 'white'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference

# Options
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cu-esiil/

extra_css:
  - stylesheets/extra.css

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
